### PR TITLE
Finalfeature Branch has all set of files included in the project Including HTML and CSS Files

### PR DESCRIPTION
**Pull request by baqar-abbas**
Finalfeature Branch has all set of files included in the project Including HTML and CSS Files, Read me file, Linters Configuration files and all the necessary files are included within the branch. Kindly share your valuable review and please approve. I need to submit today max till 7 P.M according to Program timings.

### CODE REVIEW

**Review by NduatiKagiri — COMMENTED** [review]
Hi @baqar-abbas ,

# INVALID REVIEW REQUEST ❌ ❌ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not show any commits on your project, and so I have nothing to review. It seems that you already merged your changes to the main branch. Kindly never push any changes to the main, and never merge any PR before it's reviewed and approved. Please open a Pull Request that shows all the changes you made and request for a review again. You can try to undo the merge in the previous PR, and then edit the description to meet the previous reviewer's request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by baqar-abbas** [comment]
So should I create a new repository and then create a pull request ?? Please guide @NduatiKagiri

**Comment by baqar-abbas** [comment]
Creating a new repository as discussed and will then create a new pull request to be send for review

**Comment by baqar-abbas** [comment]
Creating a new pull request and updating all files there and will send again for review as discussed with the code reviewer

**Pull request merged**
